# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-06 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_qos', '0003_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='is_monitor',
            field=models.BooleanField(default=0),
        ),
    ]
