# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-06 06:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('get_qos', '0004_auto_20180406_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='user',
        ),
        migrations.AddField(
            model_name='monitor',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
