# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-19 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_qos', '0007_auto_20180410_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50)),
                ('bandwidth', models.CharField(blank=True, max_length=50)),
                ('workload', models.CharField(blank=True, max_length=50)),
                ('qos_time', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
