# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-22 10:34
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('get_qos', '0010_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='文章详情'),
        ),
    ]
