# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-23 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_qos', '0011_auto_20180422_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qos_data',
            name='connect_time',
            field=models.FloatField(blank=True, null=True, verbose_name='DNS解析时间'),
        ),
        migrations.AlterField(
            model_name='qos_data',
            name='header_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='HTTP头部大小'),
        ),
        migrations.AlterField(
            model_name='qos_data',
            name='http_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='HTTP状态码'),
        ),
        migrations.AlterField(
            model_name='qos_data',
            name='namelookup_time',
            field=models.FloatField(blank=True, null=True, verbose_name='HTTP状态码'),
        ),
        migrations.AlterField(
            model_name='qos_data',
            name='pretransfer_time',
            field=models.FloatField(blank=True, null=True, verbose_name='建立连接到准备传输所需时间'),
        ),
        migrations.AlterField(
            model_name='qos_data',
            name='redirect_time',
            field=models.FloatField(blank=True, null=True, verbose_name='重定向所消耗的时间'),
        ),
        migrations.AlterField(
            model_name='qos_data',
            name='size_download',
            field=models.IntegerField(blank=True, null=True, verbose_name='下载数据包大小'),
        ),
        migrations.AlterField(
            model_name='qos_data',
            name='size_upload',
            field=models.IntegerField(blank=True, null=True, verbose_name='上传数据包大小'),
        ),
        migrations.AlterField(
            model_name='qos_data',
            name='speed_download',
            field=models.IntegerField(blank=True, null=True, verbose_name='平均下载速度'),
        ),
        migrations.AlterField(
            model_name='qos_data',
            name='speed_upload',
            field=models.IntegerField(blank=True, null=True, verbose_name='平均上传速度'),
        ),
        migrations.AlterField(
            model_name='qos_data',
            name='starttransfer_time',
            field=models.FloatField(blank=True, null=True, verbose_name='建立连接到传输开始所需时间'),
        ),
        migrations.AlterField(
            model_name='qos_data',
            name='total_time',
            field=models.FloatField(blank=True, null=True, verbose_name='总时间'),
        ),
        migrations.AlterField(
            model_name='qos_data',
            name='ws_url',
            field=models.CharField(default='www.baidu.com', max_length=200, verbose_name='服务地址'),
        ),
    ]
