# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-23 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_qos', '0012_auto_20180423_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='qos_data',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='价格'),
        ),
    ]
