# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-09 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_qos', '0013_qos_data_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=128)),
                ('first', models.IntegerField()),
                ('second', models.IntegerField()),
                ('log_date', models.DateTimeField()),
            ],
        ),
    ]
