# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-09 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_qos', '0014_add'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add',
        ),
    ]
