# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-16 09:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('get_qos', '0015_delete_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor_setting',
            name='total_time',
            field=models.IntegerField(blank=True, default=7),
        ),
        migrations.AddField(
            model_name='monitor_setting',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
