# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-16 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_qos', '0017_auto_20180516_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor_setting',
            name='time_interval',
            field=models.IntegerField(blank=True, default=30),
        ),
        migrations.AlterField(
            model_name='monitor_setting',
            name='total_time',
            field=models.IntegerField(blank=True, default=7),
        ),
    ]
