# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-05 15:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('get_qos', '0018_auto_20180516_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='QoS_datacaiji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ws_url', models.CharField(default='www.baidu.com', max_length=200, verbose_name='服务地址')),
                ('user_ip', models.CharField(default='0.0.0.0', max_length=20)),
                ('http_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='HTTP状态码')),
                ('namelookup_time', models.FloatField(blank=True, null=True, verbose_name='HTTP状态码')),
                ('connect_time', models.FloatField(blank=True, null=True, verbose_name='DNS解析时间')),
                ('pretransfer_time', models.FloatField(blank=True, null=True, verbose_name='建立连接到准备传输所需时间')),
                ('starttransfer_time', models.FloatField(blank=True, null=True, verbose_name='建立连接到传输开始所需时间')),
                ('redirect_time', models.FloatField(blank=True, null=True, verbose_name='重定向所消耗的时间')),
                ('total_time', models.FloatField(blank=True, null=True, verbose_name='总时间')),
                ('header_size', models.IntegerField(blank=True, null=True, verbose_name='HTTP头部大小')),
                ('size_download', models.IntegerField(blank=True, null=True, verbose_name='下载数据包大小')),
                ('size_upload', models.IntegerField(blank=True, null=True, verbose_name='上传数据包大小')),
                ('speed_download', models.IntegerField(blank=True, null=True, verbose_name='平均下载速度')),
                ('speed_upload', models.IntegerField(blank=True, null=True, verbose_name='平均上传速度')),
                ('add_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('price', models.FloatField(blank=True, null=True, verbose_name='价格')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
