# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-28 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='webservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=50)),
                ('supplier', models.CharField(max_length=200)),
                ('register_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('feature', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('ws_address', models.CharField(max_length=200)),
                ('request_method', models.CharField(max_length=50)),
                ('example', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('input_parameter', models.CharField(max_length=50)),
                ('return_parameter', models.CharField(max_length=50)),
                ('result_type', models.CharField(max_length=20)),
            ],
        ),
    ]
