# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-28 19:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ws', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webservice',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
