# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-15 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws', '0003_collection_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arma_resu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('total_time', models.FloatField()),
            ],
        ),
    ]
